source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!
banuba_sdk_version = '1.26.3'

target 'FaceAR-VE-Sample' do
  pod 'BanubaARCloudSDK', banuba_sdk_version #optional
  pod 'BanubaVideoEditorSDK', banuba_sdk_version
  pod 'BanubaAudioBrowserSDK', banuba_sdk_version #optional
  pod 'BanubaMusicEditorSDK', banuba_sdk_version
  pod 'BanubaOverlayEditorSDK', banuba_sdk_version
  pod 'BanubaEffectPlayer', banuba_sdk_version #optional
  pod 'BanubaSDK', banuba_sdk_version
  pod 'BanubaSDKSimple', banuba_sdk_version
  pod 'BanubaSDKServicing', banuba_sdk_version
  pod 'VideoEditor', banuba_sdk_version
  pod 'BanubaUtilities', banuba_sdk_version
  pod 'BanubaVideoEditorGallerySDK', banuba_sdk_version #optional
  pod 'BanubaLicenseServicingSDK', banuba_sdk_version
  pod 'BanubaVideoEditorTrimSDK', banuba_sdk_version

  pod 'VEPlaybackSDK', banuba_sdk_version
  pod 'VEEffectsSDK', banuba_sdk_version
  pod 'VEExportSDK', banuba_sdk_version

  pod 'BNBLicenseUtils', banuba_sdk_version
end
