source 'git@github.com:Banuba/specs.git'
platform :ios, '11.0'
use_frameworks!

target 'FaceAR-VE-Sample' do
   pod 'BanubaARCloudSDK', '1.24.0' #optional
  pod 'BanubaVideoEditorSDK', '1.24.0'
  pod 'BanubaAudioBrowserSDK', '1.24.0' #optional
  pod 'BanubaMusicEditorSDK', '1.24.0'
  pod 'BanubaOverlayEditorSDK', '1.24.0'
  pod 'BanubaEffectPlayer', '1.23.0' #optional
  pod 'BanubaSDK', '1.24.0' #optional
  pod 'BanubaSDKSimple', '1.24.0'
  pod 'BanubaSDKServicing', '1.24.0'
  pod 'VideoEditor', '1.24.0'
  pod 'BanubaUtilities', '1.24.0'
  pod 'BanubaVideoEditorGallerySDK', '1.24.0' #optional
  pod 'BanubaLicenseServicingSDK', '1.24.0'
  pod 'BanubaVideoEditorTrimSDK', '1.24.0'
  pod 'VEPlaybackSDK', '1.24.0'
  pod 'VEEffectsSDK', '1.24.0'
  pod 'VEExportSDK', '1.24.0'
  pod 'BanubaTokenStorageSDK', '1.24.0' #optional
  pod 'BNBLicenseUtils', '1.24'
end
