source 'git@github.com:Banuba/specs.git'
platform :ios, '11.0'
use_frameworks!

target 'FaceAR-VE-Sample' do
  pod 'BanubaVideoEditorSDK', '1.22.0'
  pod 'BanubaMusicEditorSDK', '1.22.0'
  pod 'BanubaOverlayEditorSDK', '1.22.0'
  pod 'BanubaSDKSimple', '0.22.0'
  pod 'BanubaSDKServicing', '1.22.0'
  pod 'VideoEditor', '1.22.0'
  pod 'BanubaUtilities', '1.22.0'
  pod 'BanubaVideoEditorEffectsSDK', '1.22.0'
  pod 'BanubaLicenseServicingSDK', '1.22.0'
  pod 'BNBLicenseUtils', '1.22.0'
  pod 'BanubaARCloudSDK', '1.22.0' #optional
  pod 'BanubaAudioBrowserSDK', '1.22.0' #optional
  pod 'BanubaVideoEditorGallerySDK', '1.22.0' #optional
  pod 'BanubaEffectPlayer', '1.22.0' #optional
  pod 'BanubaSDK', '1.22.0' #optional
end
